(function() {var implementors = {};
implementors["futures"] = ["impl&lt;T:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='futures/enum.Async.html' title='futures::Async'>Async</a>&lt;T&gt;","impl&lt;T:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='futures/enum.AsyncSink.html' title='futures::AsyncSink'>AsyncSink</a>&lt;T&gt;","impl&lt;F&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='futures/future/struct.Shared.html' title='futures::future::Shared'>Shared</a>&lt;F&gt; <span class='where'>where F: <a class='trait' href='futures/future/trait.Future.html' title='futures::future::Future'>Future</a></span>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='futures/task/struct.Task.html' title='futures::task::Task'>Task</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='futures/task/struct.UnparkEvent.html' title='futures::task::UnparkEvent'>UnparkEvent</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='futures/sync/oneshot/struct.Canceled.html' title='futures::sync::oneshot::Canceled'>Canceled</a>","impl&lt;T&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='futures/sync/mpsc/struct.UnboundedSender.html' title='futures::sync::mpsc::UnboundedSender'>UnboundedSender</a>&lt;T&gt;","impl&lt;T&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='futures/sync/mpsc/struct.Sender.html' title='futures::sync::mpsc::Sender'>Sender</a>&lt;T&gt;",];
implementors["futures_cpupool"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='futures_cpupool/struct.CpuPool.html' title='futures_cpupool::CpuPool'>CpuPool</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
